<?xml version="1.0" standalone="yes"?>
<!-- Automatically generated XML -->
<!DOCTYPE configrecord [
   <!ELEMENT configrecord (configgroup+)>
   <!ELEMENT configgroup (configitem+)>
   <!ELEMENT configitem (value+)>
   <!ELEMENT value (#PCDATA)>
   <!ATTLIST configrecord version CDATA #IMPLIED>
   <!ATTLIST configgroup name CDATA #IMPLIED>
   <!ATTLIST configgroup instance CDATA #IMPLIED>
   <!ATTLIST configitem name CDATA #IMPLIED>
   <!ATTLIST configitem instance CDATA #IMPLIED>
   <!ATTLIST value name CDATA #IMPLIED>
]>
<configrecord version = "0.1.0.1">   
   <configgroup name = "XML Import Control">
      <configitem name = "Restore Factory Configuration">
         <value>Disabled</value>
      </configitem>
      <configitem name = "Reboot">
         <value>Disabled</value>
      </configitem>
      <configitem name = "Missing Values">
         <value>Set to Default</value>
      </configitem>
      <configitem name = "Delete WLAN Profiles">
         <value>Enabled</value>
      </configitem>
      <configitem name = "WLAN Profile delete">
         <value name = "name"></value>
      </configitem>
   </configgroup>
</configrecord>
