<?xml version="1.0" standalone="yes"?>
<!-- Automatically generated XML -->
<!DOCTYPE configrecord [
   <!ELEMENT configrecord (configgroup+)>
   <!ELEMENT configgroup (configitem+)>
   <!ELEMENT configitem (value+)>
   <!ELEMENT value (#PCDATA)>
   <!ATTLIST configrecord version CDATA #IMPLIED>
   <!ATTLIST configgroup name CDATA #IMPLIED>
   <!ATTLIST configgroup instance CDATA #IMPLIED>
   <!ATTLIST configitem name CDATA #IMPLIED>
   <!ATTLIST configitem instance CDATA #IMPLIED>
   <!ATTLIST value name CDATA #IMPLIED>
]>
<configrecord version = "0.1.0.1">
   <configgroup name = "WLAN Profile" instance = "Radius">
      <configitem name = "Basic">
         <value name = "Network Name">Radius</value>
         <value name = "State">Enabled</value>
      </configitem>
      <configitem name = "Security">
         <value name = "Suite">WPA2</value>
         <value name = "WEP Key Size">40</value>
         <value name = "WEP TX Key Index">1</value>
         <value name = "WEP Key 1 Key"></value>
         <value name = "WEP Key 2 Key"></value>
         <value name = "WEP Key 3 Key"></value>
         <value name = "WEP Key 4 Key"></value>
         <value name = "WPAx Authentication">8021X</value>
         <value name = "WPAx Key Type">Passphrase</value>
         <value name = "WPAx Passphrase"></value>
         <value name = "WPAx Key"></value>
         <value name = "WPAx IEEE 8021X">PEAP</value>
         <value name = "WPAx Username">wcurrier</value>
         <value name = "WPAx Password">test</value>
         <value name = "WPAx Credentials"></value>
         <value name = "WPAx EAP-TTLS Option">EAP-MSCHAPV2</value>
         <value name = "WPAx PEAP ver">0</value>
         <value name = "WPAx PEAP Option">EAP-MSCHAPV2</value>
         <value name = "WPAx PEAP Credentials"></value>
         <value name = "WPAx FAST Option">MD5</value>
         <value name = "WPAx Encryption">CCMP</value>
      </configitem>
      <configitem name = "Advanced">
         <value name = "TX Power Maximum">17 dBm</value>
         <value name = "Power Management">Disabled</value>
         <value name = "PM Interval">1 beacons (100 ms each)</value>
      </configitem>
   </configgroup>
</configrecord>
