<?xml version="1.0" standalone="yes"?>
<!-- Automatically generated XML -->
<!DOCTYPE configrecord [
   <!ELEMENT configrecord (configgroup+)>
   <!ELEMENT configgroup (configitem+,configgroup*)>
   <!ELEMENT configitem (value+)>
   <!ELEMENT value (#PCDATA)>
   <!ATTLIST configrecord version CDATA #IMPLIED>
   <!ATTLIST configgroup name CDATA #IMPLIED>
   <!ATTLIST configgroup instance CDATA #IMPLIED>
   <!ATTLIST configitem name CDATA #IMPLIED>
   <!ATTLIST configitem instance CDATA #IMPLIED>
   <!ATTLIST value name CDATA #IMPLIED>
]>
<configrecord version = "0.1.0.0T0">
   <configgroup name = "tunnel connect" instance = "1">
       <configitem name = "connect mode">
           <value>Always</value>
       </configitem>
       <configitem name = "start character">
           <value>&amp;#60;control&amp;#62;B</value>
       </configitem>
       <configitem name = "flush start character">
           <value>enable</value>
       </configitem>
       <configitem name = "local port">
           <value>&amp;#60;Random&amp;#62;</value>
       </configitem>
       <configitem name = "host" instance = "1">
           <value name = "address">192.168.51.99</value>
           <value name = "port">10002 </value>
           <value name = "protocol">SSL</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "2">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "3">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "4">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "5">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "6">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "7">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "8">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "9">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "10">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "11">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "12">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "13">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "14">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "15">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host" instance = "16">
           <value name = "address"></value>
           <value name = "port">&amp;#60;None&amp;#62;</value>
           <value name = "protocol">TCP</value>
           <value name = "ssh username"></value>
           <value name = "validate certificate">enable</value>
           <value name = "tcp keep alive">45000 milliseconds</value>
           <value name = "aes encrypt key"></value>
           <value name = "aes decrypt key"></value>
       </configitem>
       <configitem name = "host mode">
           <value>Sequential</value>
       </configitem>
       <configitem name = "reconnect time">
           <value>15000 milliseconds</value>
       </configitem>
       <configitem name = "flush serial">
           <value>disable</value>
       </configitem>
       <configitem name = "block serial">
           <value>disable</value>
       </configitem>
       <configitem name = "block network">
           <value>disable</value>
       </configitem>
       <configitem name = "email connect">
           <value>&amp;#60;None&amp;#62;</value>
       </configitem>
       <configitem name = "email disconnect">
           <value>&amp;#60;None&amp;#62;</value>
       </configitem>
   </configgroup>
   <configgroup name = "ssl">
       <configitem name = "RSA certificate">
           <value name = "certificate">-----BEGIN CERTIFICATE-----
MIIDeTCCAmGgAwIBAgIJAJLPdTwe+Ap0MA0GCSqGSIb3DQEBCwUAMFMxCzAJBgNV
BAYTAmluMQswCQYDVQQIDAJ0czEMMAoGA1UEBwwDaHliMQwwCgYDVQQKDANsdHgx
DDAKBgNVBAsMA3NwYTENMAsGA1UEAwwEbmFnYTAeFw0xNjEwMjAxMzU2NDVaFw0x
OTEwMjAxMzU2NDVaMFMxCzAJBgNVBAYTAmluMQswCQYDVQQIDAJ0czEMMAoGA1UE
BwwDaHliMQwwCgYDVQQKDANsdHgxDDAKBgNVBAsMA3NwYTENMAsGA1UEAwwEbmFn
YTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALq6fylQaPrjM9No5uwI
Wjdth9+5/1at+77/re/Y1o1tHyR8sinq+wmykRb7ZLqYQRF4gzMlkxDSvp26DsEm
hxjWWJ7ri3Le1t13JzwdoJvotC0znimjFV5rsHl9ggAXFO342Gl4F+S9Dmn9eDbA
ImLwfgXXbxBmQjS8ShYVruIIvVR2Sos2hZ8G6SiVgp8ZvOAK+kYTnsWcYWW/h6x+
UQJ2NIsA8ysR4CDWJvnMuME5udgtrONH3BkzsXE+a1NAD5vjee3qb+LDqWFqKXtq
L2Mw4MSYieWtJLOc1bcbjnx3l1Y69oGZkGSwtkHOVu8Muhd3eFXi+bLOCu+FAqyu
qfcCAwEAAaNQME4wHQYDVR0OBBYEFJo7Zoya4gldnOmeWRv5tbZ8kdqUMB8GA1Ud
IwQYMBaAFJo7Zoya4gldnOmeWRv5tbZ8kdqUMAwGA1UdEwQFMAMBAf8wDQYJKoZI
hvcNAQELBQADggEBALibWvm9xDC5pEdAl74i67e1W6xXvyVSF3+Ii5p8O0+K/Kco
6CSdby2Uf9YT51S0JO50hD9xXgjBZ6BxPNeiFQRioDyrxP88B07FIN1WeXf2RfCa
OFr8ZSv90XEWTGsT3/oqvc4HJMIWrLAgCw37MEskaZUMmIwEXCFSD9HeNgMS6ok/
UJQ2psS+53M+zjbLCrThzccteYcVZ5K32zQNRnwfn6T6srOI2yiT4Ymkb85YXnP+
+5yhPfvD3nuwW5e+vD7xwdnMLmnx4O9/5DFxYcoSiBgoMAzLmUDeuIrTq4U751b3
za/ReYjleFTUEReqo9jx5XIgOiwwyZ/kn4pWGYk=
-----END CERTIFICATE-----
</value>
           <value name = "private key">-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAurp/KVBo+uMz02jm7AhaN22H37n/Vq37vv+t79jWjW0fJHyy
Ker7CbKRFvtkuphBEXiDMyWTENK+nboOwSaHGNZYnuuLct7W3XcnPB2gm+i0LTOe
KaMVXmuweX2CABcU7fjYaXgX5L0Oaf14NsAiYvB+BddvEGZCNLxKFhWu4gi9VHZK
izaFnwbpKJWCnxm84Ar6RhOexZxhZb+HrH5RAnY0iwDzKxHgINYm+cy4wTm52C2s
40fcGTOxcT5rU0APm+N57epv4sOpYWope2ovYzDgxJiJ5a0ks5zVtxuOfHeXVjr2
gZmQZLC2Qc5W7wy6F3d4VeL5ss4K74UCrK6p9wIDAQABAoIBAGYYfFihf5TVz0tj
Swd5FaLCv4zjDKpfHIt1DqxaWg0fwexYRa3HrhTCTrRLJeskPkeIJew8OinzoIdq
6JBROYKqB/B0h116W+7hLFGhPWShmoowc+T+JzvmE6qJph/YfvgSnHkmUaIegJgR
H76H1QVVywH0peRIlSByZuumVWV+RKVDUub7juRnE1oJVgYpY1GPcoYdjkZPC9Oo
BlA6hLfpj5z1LjORQgm37N5rvRxUCi1fiz8d0vHhbQlHTaELwYX++GVC/cRwD3t5
fW082rV1ftIBbmuXzbmd3Sd/Zfw2kbZxwZu2lywC0aa+OQG19D2JlartULtKfJ6O
JhGcVUECgYEA4CGyz5RB/tDia8+9lwv3qMm8kohtZE+WfMQ0jGRgxFFIdPPYOq25
xEZO29SAVqDBxZ1LtGiCQYBho8iDUUvD1DgC+76RMCZ+7K71bALhiTSl9NgQao1O
VpZMgwELK7Z4Ml3gcWw0NlCeF0bPl2Yv75xEehD6QekhMobqpTpQq9cCgYEA1UdW
2c1sH0yyMMRaNaK54EjW2HdI9unAHxDk72CoOh92aKmitSeyEnHfYpc1ihHi1egn
fKaSouhno+tMcBfzNVOR+YsJAvwah4hrX+0KTa0zn7vrobadn01nl/NhEc91tf41
Yjddi0T5p34M2Hfx9a+pIuMPvgU4kO4YUiVxLuECgYEApQkLQoA3rCshXiOExfEg
9p89hGSCsEdOVyaeTvYmrsfvY3aeNG7xh84BiStLKP6MUDfHo9sEdrjSrKgb0cPJ
Ob3YrIghHmRqN1uJCXSBn+ctgEGMrPjJw0Y+poQhNpnQnb20Y7A6LfhkwFz6xM+Q
4o2deoh/zgKc2DiyFOIAvtcCgYAE1Sn9o274wpcjDb/xiS9nCp97pjBMD/3fdlWJ
qwoEzyOyuW1LZ4vcaSIjrMN0znTyXeFPLMMT1+pJR5Ki05gaNDuRiPn6TFYZjhjI
wqlCG1OZIfvz3RxzOKDJS6V+btH+/rSc9h4zgquZhPyrhwQ/iexuMvDvYFToy8xX
SCvpYQKBgA5QJfKCZW4mr1Cgtw7xNQWbrGssN207vh0c/bZIPmr4WB5ESCzKTIgR
7aTrQVZFPqihtA7/o00LzQ08EJ1g5F0VsRx33HoH9YXCemfZt8Qd92aoNsVtPl/z
liHEPPrSDe8WRZAOODasDOdmzLAy2FFm968qGYyUiLmo2re/rouA
-----END RSA PRIVATE KEY-----
</value>
       </configitem>
       <configitem name = "trusted ca" instance = "0">
           <value>-----BEGIN CERTIFICATE-----
MIIDeTCCAmGgAwIBAgIJAJLPdTwe+Ap0MA0GCSqGSIb3DQEBCwUAMFMxCzAJBgNV
BAYTAmluMQswCQYDVQQIDAJ0czEMMAoGA1UEBwwDaHliMQwwCgYDVQQKDANsdHgx
DDAKBgNVBAsMA3NwYTENMAsGA1UEAwwEbmFnYTAeFw0xNjEwMjAxMzU2NDVaFw0x
OTEwMjAxMzU2NDVaMFMxCzAJBgNVBAYTAmluMQswCQYDVQQIDAJ0czEMMAoGA1UE
BwwDaHliMQwwCgYDVQQKDANsdHgxDDAKBgNVBAsMA3NwYTENMAsGA1UEAwwEbmFn
YTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALq6fylQaPrjM9No5uwI
Wjdth9+5/1at+77/re/Y1o1tHyR8sinq+wmykRb7ZLqYQRF4gzMlkxDSvp26DsEm
hxjWWJ7ri3Le1t13JzwdoJvotC0znimjFV5rsHl9ggAXFO342Gl4F+S9Dmn9eDbA
ImLwfgXXbxBmQjS8ShYVruIIvVR2Sos2hZ8G6SiVgp8ZvOAK+kYTnsWcYWW/h6x+
UQJ2NIsA8ysR4CDWJvnMuME5udgtrONH3BkzsXE+a1NAD5vjee3qb+LDqWFqKXtq
L2Mw4MSYieWtJLOc1bcbjnx3l1Y69oGZkGSwtkHOVu8Muhd3eFXi+bLOCu+FAqyu
qfcCAwEAAaNQME4wHQYDVR0OBBYEFJo7Zoya4gldnOmeWRv5tbZ8kdqUMB8GA1Ud
IwQYMBaAFJo7Zoya4gldnOmeWRv5tbZ8kdqUMAwGA1UdEwQFMAMBAf8wDQYJKoZI
hvcNAQELBQADggEBALibWvm9xDC5pEdAl74i67e1W6xXvyVSF3+Ii5p8O0+K/Kco
6CSdby2Uf9YT51S0JO50hD9xXgjBZ6BxPNeiFQRioDyrxP88B07FIN1WeXf2RfCa
OFr8ZSv90XEWTGsT3/oqvc4HJMIWrLAgCw37MEskaZUMmIwEXCFSD9HeNgMS6ok/
UJQ2psS+53M+zjbLCrThzccteYcVZ5K32zQNRnwfn6T6srOI2yiT4Ymkb85YXnP+
+5yhPfvD3nuwW5e+vD7xwdnMLmnx4O9/5DFxYcoSiBgoMAzLmUDeuIrTq4U751b3
za/ReYjleFTUEReqo9jx5XIgOiwwyZ/kn4pWGYk=
-----END CERTIFICATE-----
</value>
       </configitem>
       <configitem name = "delete all cas">
           <value>enable</value>
       </configitem>
   </configgroup>
</configrecord>
