<?xml version="1.0" standalone="yes"?>
<!-- Automatically generated XML -->
<!DOCTYPE configrecord [
   <!ELEMENT configrecord (configgroup+)>
   <!ELEMENT configgroup (configitem+,configgroup*)>
   <!ELEMENT configitem (value+)>
   <!ELEMENT value (#PCDATA)>
   <!ATTLIST configrecord version CDATA #IMPLIED>
   <!ATTLIST configgroup name CDATA #IMPLIED>
   <!ATTLIST configgroup instance CDATA #IMPLIED>
   <!ATTLIST configitem name CDATA #IMPLIED>
   <!ATTLIST configitem instance CDATA #IMPLIED>
   <!ATTLIST value name CDATA #IMPLIED>
]>
<configrecord version = "0.1.0.0T0">
   <configgroup name = "tunnel accept" instance = "1">
       <configitem name = "accept mode">
           <value>Always</value>
       </configitem>
       <configitem name = "start character">
           <value>&amp;#60;control&amp;#62;B</value>
       </configitem>
       <configitem name = "flush start character">
           <value>enable</value>
       </configitem>
       <configitem name = "local port">
           <value>10001 </value>
       </configitem>
       <configitem name = "protocol">
           <value>TCP AES</value>
       </configitem>
       <configitem name = "tcp keep alive">
           <value>45000 milliseconds</value>
       </configitem>
       <configitem name = "aes encrypt key">
           <value>11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11</value>
       </configitem>
       <configitem name = "aes decrypt key">
           <value>11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11</value>
       </configitem>
       <configitem name = "flush serial">
           <value>disable</value>
       </configitem>
       <configitem name = "block serial">
           <value>disable</value>
       </configitem>
       <configitem name = "block network">
           <value>disable</value>
       </configitem>
       <configitem name = "password">
           <value name = "password"></value>
           <value name = "prompt">disable</value>
       </configitem>
       <configitem name = "email connect">
           <value>&amp;#60;None&amp;#62;</value>
       </configitem>
       <configitem name = "email disconnect">
           <value>&amp;#60;None&amp;#62;</value>
       </configitem>
   </configgroup>
</configrecord>